version: '0'
services:
  backend:
    build: backend/
    image: backend
    ports:
      - "7001:7001"
    volumes:
      - ./backend/app:/app
<<<<<<< Updated upstream
    restart: always
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7001"]
=======
    depends_on:
      - cache
    command: "python main.py"

  topic_generation:
    build: ai/bertopic/
    image: topic_generation:latest
    ports:
      - 8080:8080
    volumes:
      - ./ai/bertopic/app:/app
    command: "python main.py"

# hi
>>>>>>> Stashed changes
